# Generated by Django 4.1.5 on 2023-01-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=150)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('toy_category', models.CharField(db_column='toyCategory', default='', max_length=150)),
                ('release_date', models.DateTimeField(db_column='releaseDate')),
                ('was_included_in_home', models.BooleanField(db_column='wasIncludedInHome', default=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
